a = float(input("Initial deposit: "))
b = float(input("annual interest rate: "))
c = int(input("Enter number of years: "))
d = a * ((1 + b/1200)**(12*c))         
print(f"Balance after {c} years: {d:.02f}")         