s = input()
z = input()
k = len(s)
l = len(z)
s = s.upper()
z = z.upper()
print (s, z, sep=" ")
print ("initials: ", s[0], "." , z[0], ".",  sep="")
print("letters:",str(k), "+", str(l), "=", k + l, sep=" ")
